#!/usr/bin/python
from astropy.io import fits
from rts2 import scriptcomm
from scottSock import scottSock
from rts2solib import focalfit

import os
sepPresent = False
try:
	import sep
	sepPresent = True
except Exception as ex:
	pass


class ShiftFocus (scriptcomm.Rts2Comm):
	"""Take and process focussing data."""

	def __init__(self,exptime = 10,step=20,attempts=10,filterGalaxies=False):
		scriptcomm.Rts2Comm.__init__(self)
		self.log('I', 'This is a test')
		self.exptime = exptime
		self.step = step
		self.focuser = "F0"
		self.attempts = attempts

		# if |offset| is above this value, try linear fit
		self.linear_fit = self.step * self.attempts / 2.0
		# target FWHM for linear fit
		self.linear_fit_fwhm = 3.5
		self.filterGalaxies = filterGalaxies

	def shift_focus( self ):
		self.setValue("shiftfocus", 1, "C0")
		#self.setValue( "exposure", 5 )
		#img = self.exposure( self.before_readout, "%b/queue/%N/%c/%t/%f" )
		n_shifts = int(self.getValue( "SHIFT_N", "C0" ))
		shift_fo= int(self.getValue( "SHIFT_FO", "C0" ))
		focpos = float(self.getValue("FOC_TAR", self.focuser).split()[0])
		self.setValue("FOC_TAR", focpos-((n_shifts*shift_fo)/2.0), self.focuser)
		img = self.exposure( self.before_readout, '%b/queue/%f' )
                to_dataserver(img)
		#call focalfit
		focfit = focalfit(img)
		focalvalue_fit, flags = focfit.run()

                if len([f for f in flags if f == 2]) > 0:
                    self.log('I', "some fits were high ended, maybe start with the initial focal position higher")
                if len([f for f in flags if f == 1]) > 0:
                    self.log('I', "some fits were low ended, maybe start with the initial focal poistion lower")
                if len([f for f in flags if f == 0]) > 0:
                    self.log('I', str(len([f for f in flags if f == 0])) + " good fits for returned focal value")
                if len(flags) == 0:
                    self.log('I', "No groupings found, attempt longer exposures or different position")

		self.log('I', "setting focus to "+str(focalvalue_fit))
		self.setValue("FOC_TAR", focalvalue_fit, self.focuser)		
		self.setValue("shiftfocus", 0, "C0")
		#to_dataserver( img )
		

	def before_readout(self):
		
		self.log( 'I', 'Before readout' )

	def run( self ):
		self.shift_focus()

def to_dataserver( fname, outfile='test.fits', clobber=True ):

	fitsfd = fits.open( fname )
		

        width = 0
        height = 0
        i=0
        for ext in fitsfd:
                if hasattr( ext, 'data' ):
                        if ext.data is not None:
                            try:
                                width+=ext.data.shape[0]
                                height+=ext.data.shape[1]
                                i+=1
                            except Exception as err:
                                pass

        fitsfd.close()
        fsize = os.stat(fname).st_size

        fd = open(fname, 'rb')


        if clobber:
                clobber_char = '!'
        else:
                clobber_char = ''
        meta = "          {} {}{} 1 {} {} 0".format( fsize, clobber_char, '/home/rts2obs/shiftfocus.fits', width, height )
        meta = meta + (256-len(meta))*' '

        data = meta+fd.read()
        lendata = len(data)
        soc = scottSock( '10.30.1.1', 6543 )

        counter = 0
        socsize = 1024
        buffsize = 0
        while buffsize < len(data):
                sent = soc.send( data[buffsize:buffsize+1024] )
                buffsize+=sent


f=ShiftFocus()

f.run()

